resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe-split.yml@templates
  parameters:
    package: openscenegraph
    package_version: 3.6.5
    destination_repository: ccdc-3rdparty-conan
    build_types:
      - Release
      - Debug
    use_release_zlib_profile: True
