resources:
  repositories:
    - repository: templates
      type: git
      name: ccdc-3rd-party/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-local-recipe.yml@templates
  parameters:
    package: openscenegraph
    package_version: 3.6.3
    destination_repository: ccdc-3rdparty-conan
    artifactory_api_key: $(artifactory.api.key)
    build_types:
      - Release
      - Debug
